### PR TITLE
Fix travis ci issues

### PR DESCRIPTION
**Pull request by amcp**

### CODE REVIEW

**Comment by F2006** [comment]
Great thanks. I was also looking in to this yesterday and will also today. Seems like the problem is the Travis container environment, setting sudo to true in the Travis config seems to have some success.

Might not be a bad idea for now to use a VM for the build, since it has more memory and the CPU can burst, but it would be good to understand why the container setup does not work. 

https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

I had some success in the container, but it seems like Dynamo disappears during the first few tests (if you scroll down to the bottom of the log) and then just fails to connect https://s3.amazonaws.com/archive.travis-ci.org/jobs/223342616/log.txt

**Comment by amcp** [comment]
Unfortunately the only resource I found on running DynamoDB Local in Travis CI was in Japanese, but here goes:
http://dev.classmethod.jp/cloud/aws/travis-ci-dynamodb-local-2/
It seems like Travis CI containers are memory constrained, so one needs to run local with a smaller memory footprint. If sudo mode is giving you more success, then I definitely would try that.

**Comment by amcp** [comment]
@F2006 I've gotta go to bed now so can you triage the build in progress for this PR and see if you can 1 reduce the log output and 2 identify any failures?

**Comment by F2006** [comment]
@amcp my guess would also be that Dynamo is running out of memory and crashing while running in the Travis CI container. The VM has 3.5GB more memory than the container (only has 4GB) and I don't see any reason for the project to have to run in a container. 

To clean up the logs, just set the log level for ElasticSearch. Here is the configuration changes for the log4j properties file, if you would like to add them to your branch, then we can keep all the changes to get the build running again in one pull requests?

Log4j config changes:
```
log4j.logger.com.thinkaurelius=ERROR
log4j.category.org.elasticsearch=ERROR
log4j.logger.com.amazonaws=ERROR
```

I have set thinkaurelius and amazonaws to ERROR, so that any errors during the tests can surface in the log.

The second issue is the build running for more than 10min with no log output, Travis CI terminates the build at the 10min time limit.

Either the tests are taking a long time to execute (which does not seem right) or a test is hanging. Wrapping the command with `travis_wait` and extending the 10min time limit to 120min also does not solve the problem, it only got to 48 of 120 tests in 49min, making a hanging test more plausible.

https://travis-ci.org/nichestreem/dynamodb-titan-storage-backend/jobs/223733287

Looking at this build, it got to MultiDynamoDBGraphTest and then terminated, it might be the first clue.

https://travis-ci.org/nichestreem/dynamodb-titan-storage-backend/jobs/223712625

I'm not familiar with the tests, but I'll start digging into them tomorrow as the day goes and see if I can find something in there.

**Comment by amcp** [comment]
@F2006 I want you to get credit as well, so I'll set up a feature branch that we can do PRs off and you can include your commits as well. I may end up closing this one in favor of the feature branch.

**Comment by F2006** [comment]
@amcp great, sounds good. I'll branch on my side for the log4j changes and open a PR against the new branch when its created. I'll dive into the tests today as the day goes and see if I can find something.

**Comment by amcp** [comment]
@F2006 I am ready to create the feature branch for you. I am thinking of applying your changes to the new feature branch and we can review/work together.

**Comment by F2006** [comment]
@amcp, sorry, been a busy last few days, that sounds good. Let me know when it is created, then I'll open a pull request for the log4j changes. 

I have done some investigation into the builds failing over the last few days. Both builds on Travis CI was running both the single and multi tests. I have fixed the Travis CI config to correctly split the builds, but the total build time is still being terminated at 50min.

I have enabled Titans metrics to print stats to the console every 8min, this is also a nice way to keep the build alive and avoid the 10min timeout if there is no output from the tests.

There are a hand full of actions taking a long time to execute, for example:
(https://s3.amazonaws.com/archive.travis-ci.org/jobs/224456475/log.txt)

```
d.UpdateItem.MULTI_graphindex
             count = 61328
         mean rate = 25.67 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.93 calls/second
    15-minute rate = 9.84 calls/second
               min = 3.55 milliseconds
               max = 2009.97 milliseconds
              mean = 629.99 milliseconds
            stddev = 485.95 milliseconds
            median = 525.72 milliseconds
              75% <= 973.08 milliseconds
              95% <= 1497.79 milliseconds
              98% <= 1805.20 milliseconds
              99% <= 1866.89 milliseconds
            99.9% <= 2009.35 milliseconds 
```
The next step was to profile the local instance of DynamoDB. Threads seems to spend quite some time to acquire a read lock around sqlite and this looks to be the performance hit. My understanding when adding the `inMemory`  flag when starting DynamoDB local, is that all data will be kept in memory and not to disk as well? If that is the case and no data should be saved to disk, then it might be a bug in DynamoDB local.

screen shot 2017-04-21 at 3 51 10 pm

image

I have also profiled the same unit test used to profile DynamoDB local (MultiDynamoDBGraphTest.testVertexCentricQuery) and nothing stood out as a performance bottle neck. The top function is reading from the comms socket, which is expected, the rest of the threads are merely just waiting around.

screen shot 2017-04-21 at 3 32 09 pm

I have also adjusted the parameters for Dynamo to increase throughput and avoid throttling in the connector it-self. It got the runtime for the unit test down from 12min to 7min on my machine, but I don't think adjusting the parameters to ridiculously high numbers is the correct direction, since people use that as examples and throttling should still be tested.

Moving forward, it will be good to understand what the `inMemory` flag actually do and is the behaviour seen correct.

For this project, we could split the unit tests into more groups that would keep the runtime below 50min for each group and run each group as a separate build on Travis CI. I'll be happy to do the split on the builds if you think we should move into this direction.

**Comment by amcp** [comment]
Thank you for the detailed analysis. I think we should split the builds.

**Comment by amcp** [comment]
@F2006 lets move this discussion to an issue.

**Pull request closed without merging**
