### PR TITLE
Update dynamodb-local pom.xml

### PR DESCRIPTION
**Pull request by apivovarov**

### CODE REVIEW

**Comment by apivovarov** [comment]
https dynamodb-local repo URL
https://forums.aws.amazon.com/ann.jspa?annID=3148

**Comment by apivovarov** [comment]
http access to dynamodb-local repo will be disabled on Feb 6th, 2017. Please merge this PR ASAP.

**Comment by apivovarov** [comment]
@amcp

**Comment by jfstephe** [comment]
@apivovarov - Was that the only change that was required? When I tried that earlier today in an attempt to fix the issue you referenced above, it didn't work. I had to change the aws sdk version to 1.11.0.1 from 1.10.x.x. The tests didn't work for me either then, but that could be my local machine as the issue was fixed before I could investigate (and the tests take several hours to run... ....apparently).

**Comment by apivovarov** [comment]
@jfstephe I tried to build dynamodb-titan-storage-backend with the fix in pom.xml
it works!
```
....
Downloading: https://s3-us-west-2.amazonaws.com/dynamodb-local/release/com/amazonaws/DynamoDBLocal/1.11.0.1/DynamoDBLocal-1.11.0.1.jar
...
[INFO] BUILD SUCCESS

```

**Pull request merged**
